[package]
name = "simdjson-sys"
version = "0.1.0-alpha.2"
edition = "2021"
license = "Apache-2.0"
description = "Low level Rust bindings for simdjson."
homepage = "https://crates.io/crates/simdjson-sys"
documentation = "https://docs.rs/simdjson-sys"
repository = "https://github.com/SunDoge/simdjson-rust/tree/master/simdjson-sys"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
exclude = ["simdjson/", "!simdjson/singleheader/simdjson.*"]

[dependencies]
cxx = "1.0.197"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.197"
