cmake_minimum_required(VERSION 3.15)
project(simdjson_sys LANGUAGES CXX)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_library(simdjson STATIC vendor/simdjson/simdjson.cpp)
set_target_properties(simdjson PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(simdjson PUBLIC vendor/simdjson)
install(TARGETS simdjson ARCHIVE DESTINATION lib)
install(FILES vendor/simdjson/simdjson.h DESTINATION include)
